apiVersion: v1
kind: Service
metadata:
  name: clouds-integration
  namespace: dumb
spec:
  selector:
    app: clouds-integration
  type: NodePort
  ports:
    - name: http
      port: 7100
      nodePort: 30100
      targetPort: http