apiVersion: v1
kind: Service
metadata:
  name: clouds
  namespace: default
spec:
  selector:
    app: clouds
  type: NodePort
  ports:
    - name: http
      port: 7000
      nodePort: 30000
      targetPort: http